version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./compose/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
